routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/home', 'HomeController@index')->name('home');



Route::group(['prefix' => 'auth','as' => 'auth.','namespace' => 'Auth'],function(){
	Route::get('/login', 'LoginController@showForm')->name('form');
	Route::post('/login', 'LoginController@login')->name('login');
	Route::get('/logout', 'LoginController@logout')->name('logout');
});


Route::group(['middleware' => 'auth'],function() {
	Route::get('/', 'ReporterController@index');


	Route::resource('anggota','AnggotaController',['parameters' => [
	    'anggota' => 'data'
	]]);


	Route::resource('tabungan','TabunganController',['parameters' => [
	    'tabungan' => 'data'
	],'except' => ['edit','update']]);


	Route::get('tabungan/{data}/transact','TabunganController@form_transact')->name('tabungan.form_transact');
	Route::post('tabungan/{data}/transact','TabunganController@transact')->name('tabungan.transact');


	Route::get('tabungan/{data}/riwayat','RiwayatController@index')->name('riwayat.list_transact');
	Route::get('tabungan/riwayat/{data}/detail','RiwayatController@detail')->name('riwayat.detail_transact');




	Route::resource('peminjaman','PeminjamanController',['parameters' => [
	    'peminjaman' => 'data'
	]]);


	Route::get('angsuran/{peminjaman}/list','AngsuranController@index')->name('peminjaman.list_angsuran');
	Route::get('angsuran/{peminjaman}/{data}/edit','AngsuranController@edit')->name('angsuran.edit');
	Route::put('angsuran/{peminjaman}/{data}/edit','AngsuranController@update')->name('angsuran.update');
	Route::get('setting','CmsController@edit')->name('cms.index');


	Route::get('change_password','Auth\AuthController@change_password_form')->name('auth.change_password.form');
	Route::post('change_password','Auth\AuthController@change_password')->name('auth.change_password');






	Route::resource('user','UserController',['parameters' => [
	    'user' => 'data'
	]]);
});

Route::group(['prefix' => 'reports'],function(){
	// Route::get('/anggota', 'AnggotaController@exportAnggota');
	// Route::get('/peminjaman', 'PeminjamanController@exportPeminjaman');
	Route::post('/tabungan/{tabungan}/history', 'TabunganController@exportHistory')->name("reports.tabungan.history");
});

app/Models/Riwayat.php
<?php

namespace App\Models;;

use Illuminate\Database\Eloquent\Model;

class Riwayat extends Model
{
    //
    protected $table = "riwayat_tabungan";

    protected $fillable = [
    	"tabungan_id",
        "no_rekening",
        "action",
        "value",
        "created_by"
    ];

    public function anggota(){
        return $this->belongsTo('App\Models\Anggota','id');
    }
    public function angsuran(){
        return $this->hasMany('App\Models\Angsuran');
    }
}

app/Http/Controllers/RiwayatController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use App\Models\Tabungan;
use App\Models\Riwayat;

class RiwayatController extends Controller {
	private $actionRoutes = "riwayat";

	public function index($id) {
		$riwayat = Riwayat::where(["tabungan_id" => $id])->orderBy('created_at','DESC')->paginate(10);
		
		return view($this->actionRoutes. '.index',[
			"data" => $riwayat,
			"id" => $id,
			"title" => ucfirst($this->actionRoutes),
			"actionRoutes" => $this->actionRoutes
		]);
	}

	public function detail(Riwayat $data){
		$riwayat = $data
					->where(['riwayat_tabungan.id' => $data->id])
					->join('tabungan','tabungan_id','=','tabungan.id')
					->join('anggota','tabungan.anggota_id','=','anggota.id')
					->select([
						"riwayat_tabungan.tabungan_id",
						"tabungan.no_rekening",
						DB::raw("anggota.nama AS nama_nasabah"),
						DB::raw("riwayat_tabungan.action AS Aksi"),
						"riwayat_tabungan.value",
					])
					->first();

		
		$riwayat->Aksi = ($riwayat->Aksi == "simpan") ? "Penambahan Saldo" : "Pengambilan Saldo";
		$riwayat->value = "Rp ". \Str::toRp($riwayat->value);

		return view($this->actionRoutes. '.show',[
			"data" => $riwayat,
			"title" => ucfirst($this->actionRoutes),
			"actionRoutes" => $this->actionRoutes
		]);
	}

}

resources/views/riwayat/index.blade.php
@extends('layouts.main')

@section('title')
List {{ $title }}
@endsection
@section('header-title')
List {{ $title }}
@endsection

@section('content')
<!-- Modal -->
<form action="{{ route("reports.tabungan.history",[ "id" => $id]) }}" method="post">
    <div class="modal fade" id="modallaporan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Cetak Riwayat</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    @method("POST")
                    @csrf
                    <div class="form-group">
                        <label for="month">Pilih Bulan</label>
                        <input type="month" id="month" name="month" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <span type="button" class="btn btn-default" data-dismiss="modal">Kembali</span>
                    <button class="btn btn-primary">Cetak</button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="col-md-12">
    <div class="card card-default">
        <div class="card-header">
            <?= HtmlHelper::a(route('tabungan.show',["data" => $id]),['class' => 'btn btn-danger mt1 mr-1'])->label('Cancel')->get() ?>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modallaporan">
                Cetak Laporan
            </button>
        </div>
        <div class="card-body">
            <div class="table-sm-responsive">
                <table class="table table-hover table-borderless">
                    <thead>
                        <th>#</th>
                        <th>Tanggal Transaksi</th>
                        <th>Aksi</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                        <?php 

							if(isset($_GET['page'])){
								$no = (((0 + $_GET['page'])*10)+1)-10;
							}else{
								$no = 1;
							}
							?>
                        @foreach($data as $row)
                        <tr>
                            <td>
                                {{ $no++ }}
                            </td>
                            <td>
                                {{ Str::date($row->created_at) }}
                            </td>
                            <td>
                                {{ ($row->action == "simpan") ? "Penambahan Saldo" : "Pengambilan Saldo" }}
                            </td>
                            <td>
                                <?= HtmlHelper::a(
												route($actionRoutes . ".detail_transact",["data" => $row->id]),
												[
													"class" => "btn btn-default"
												]
											)
											->label("Detail")->get()
										  ?>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="mt-3">
                {{ $data->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/riwayat/show.blade.php
@extends('layouts.main')


@section('title')
	Detail {{ $title }}
@endsection
@section('header-title')
	Detail {{ $title }}
@endsection

@section('content')
  <div class="col-md-12">
    <?= LaraYii::alert($errors) ?>
    <div class="mb-1"></div>
    
    <div class="card card-default">
      <div class="card-header">
        <?= HtmlHelper::a(route($actionRoutes.'.list_transact',["data" => $data->tabungan_id]),['class' => 'btn btn-danger mt1 mr-1'])->label('Cancel')->get() ?>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive">
        <?= ListView::generate($data, 
            $withouts = ['id','created_at','updated_at','password'],
            [
              "class" => "table table-borderless table-hover"
            ]
            ) ?>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
@endsection