routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/home', 'HomeController@index')->name('home');



Route::group(['prefix' => 'auth','as' => 'auth.','namespace' => 'Auth'],function(){
	Route::get('/login', 'LoginController@showForm')->name('form');
	Route::post('/login', 'LoginController@login')->name('login');
	Route::get('/logout', 'LoginController@logout')->name('logout');
});


Route::group(['middleware' => 'auth'],function() {
	Route::get('/', 'ReporterController@index');


	Route::resource('anggota','AnggotaController',['parameters' => [
	    'anggota' => 'data'
	]]);


	Route::resource('tabungan','TabunganController',['parameters' => [
	    'tabungan' => 'data'
	],'except' => ['edit','update']]);


	Route::get('tabungan/{data}/transact','TabunganController@form_transact')->name('tabungan.form_transact');
	Route::post('tabungan/{data}/transact','TabunganController@transact')->name('tabungan.transact');


	Route::get('tabungan/{data}/riwayat','RiwayatController@index')->name('riwayat.list_transact');
	Route::get('tabungan/riwayat/{data}/detail','RiwayatController@detail')->name('riwayat.detail_transact');




	Route::resource('peminjaman','PeminjamanController',['parameters' => [
	    'peminjaman' => 'data'
	]]);


	Route::get('angsuran/{peminjaman}/list','AngsuranController@index')->name('peminjaman.list_angsuran');
	Route::get('angsuran/{peminjaman}/{data}/edit','AngsuranController@edit')->name('angsuran.edit');
	Route::put('angsuran/{peminjaman}/{data}/edit','AngsuranController@update')->name('angsuran.update');
	Route::get('setting','CmsController@edit')->name('cms.index');


	Route::get('change_password','Auth\AuthController@change_password_form')->name('auth.change_password.form');
	Route::post('change_password','Auth\AuthController@change_password')->name('auth.change_password');






	Route::resource('user','UserController',['parameters' => [
	    'user' => 'data'
	]]);
});

Route::group(['prefix' => 'reports'],function(){
	// Route::get('/anggota', 'AnggotaController@exportAnggota');
	// Route::get('/peminjaman', 'PeminjamanController@exportPeminjaman');
	Route::post('/tabungan/{tabungan}/history', 'TabunganController@exportHistory')->name("reports.tabungan.history");
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <title>test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="csrf_token" content="{{ csrf_token() }}">
    <link rel="stylesheet" type="text/css" href="/css/grid.css">
    <link rel="stylesheet" type="text/css" href="/css/base.css">
  <style type="text/css">
    
        /* Let's get this party started */
        ::-webkit-scrollbar {
            width: 8px;
        }
         
        /* Track */
        ::-webkit-scrollbar-track {
        }
         
        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: rgba(145,154,213,0.8);
        }
        ::-webkit-scrollbar-thumb:window-inactive {
            background: rgba(105,94,153,0.8);
        }
  </style>
    <style type="text/css">
        html{
            font-family: Poppins;
        }
        body {
            background-image: url('/uploaded/login/login_base.jpg');
            background-size: cover;
            height: 100vh;
            margin: 0;
            font-size: 14px;
            color: #666;
        }
        h1 {
            font-size: 24px;
            margin: 0 auto;
            text-align: center;
            color: #11151a;
        }
        h2 {
            font-size: 42px;
            margin: 0;
        }
        .login_page img {
        }
        .error_text {
            color: #aaa;
        }
        a {
            color: #55a3d1;
            padding: 5px 0;
            text-decoration: none;
        }
        .container {
            width: 80%;
            margin: auto;
        }



        .boxed {
            margin: auto!important;
            padding: 40px;
            box-shadow: 0 0 10px #efefef;
            border-radius: 10px;
            background-color: rgba(255,255,255,.9);
        }
        .m-auto {
            margin: 0 auto
        }

        .boxed__content {
            padding-top: 30px;
        }
        .boxed__content .form-group {
            padding: 10px 0;
        }

        .boxed__content .form-group label {
            margin-bottom: 5px;
        }
        .boxed__content .form-group input {
            width: 100%;
            padding: 5px;
            border: 1px solid #eee;
            border-radius: 3px;
        }
        .btn {
            margin: 0 auto;
            border: 1px solid transparent;
            padding: 10px 20px;
            display: block;
            border-radius: 4px;
        }
        .btn-primary {
            background-color: #3465D9;
            color: #fff;
        }
        .boxed__content .form-group button {
            margin: 0 auto;
        }

        .img-responsive {
            margin: 0 auto;
            width: 100%;
            height: 100px;
            /*max-height: ;*/
        }

        label {
            display: block;
        }

        .alert {
            display: block;
            border-radius: 5px;
            border: 1px solid #ddd;
            padding: 5px 10px;
            background-color: #eee;
            position: relative;
            color: #fff;
        }
        .alert .close {
            float: right;
            color: #fff;
            font-size: 18px;
            background-color: transparent;
            border: 0;
        }
        .alert .close:focus {
            outline: none;
        }
        .alert.alert-success {
            background-color: #8ee5a3;
        }
        .alert.alert-danger {
            background-color: #f25252;
        }


    </style>
</head>
<body>
    <div class="login_page">
        <div class="container pv-6">
            <div class="row">
                <div class="col-md-6 col-sm-8 col-xs-12 m-auto">
                    <div class="boxed">
                        <h1 class="boxed__title">Login Page</h1>
                        <div class="boxed__content">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        alertClose = document.querySelector('.alert .close')
        alertClose.addEventListener('click',() => {
            console.log(alertClose.parentElement.style.display = 'none' );
        })

    </script>
</body>
</html>

resources/views/layouts/css.blade.php
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/fa/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/css/adminlte.min.css">
  <link rel="stylesheet" href="/css/select2.min.css">
  <link rel="stylesheet" href="/css/select2-bootstrap4.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <style type="text/css">
  	
		/* Let's get this party started */
		::-webkit-scrollbar {
		    width: 8px;
		}
		 
		/* Track */
		::-webkit-scrollbar-track {
		}
		 
		/* Handle */
		::-webkit-scrollbar-thumb {
		    background: rgba(145,154,213,0.8);
		}
		::-webkit-scrollbar-thumb:window-inactive {
		    background: rgba(105,94,153,0.8);
		}
  </style>

resources/views/layouts/js.blade.php
<!-- jQuery -->
<script src="/js/jquery.min.js"></script>
<!-- jQuery UI -->
<script src="/js/jquery-ui.min.js"></script>
<!-- Bootstrap -->
<script src="/js/bootstrap.min.js"></script>
<!-- Select2 -->
<script src="/js/select2.full.min.js"></script>
<!-- Summer Note -->
<script src="/js/summernote.min.js"></script>
<!-- Moment -->
<script src="/js/moment.min.js"></script>
<!-- AdminLTE App -->
<script src="/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="/js/pages/dashboard.js"></script> -->
<!-- AdminLTE for demo purposes -->
<script src="/js/demo.js"></script>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title')</title>
  <!-- Tell the browser to be responsive to screen width -->
  @include('layouts.css')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  @include('layouts.navbar')
  @include('layouts.sidebar')


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark"><b>@yield('header-title')</b></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">@yield('header-title')</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            @yield('content')
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; <?= Date('Y') ?> <a href="#">{{ config('app.name') }}</a>.</strong>
    All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
@include('layouts.js')
@yield('_js')
</body>
</html>

resources/views/layouts/navbar.blade.php
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link"><?= Auth::user()->nama ?> ( <?= Auth::user()->username ?> )</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{ route('auth.logout') }}" class="nav-link">logout</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/layouts/sidebar.blade.php
<?php

$sidebar = [
  [
    "title" => "Dashboard",
    "link" => "/",
    "icon" => "fas fa-tachometer-alt",
    "children" => []
  ],
  [
    "title" => "Menu Master",
    "link" => "#",
    "icon" => "fas fa-th",
    "children" => [
      [
        "title" => "Anggota",
        "link" => route('anggota.index'),
        "icon" => "",
      ],
      [
        "title" => "User",
        "link" => route('user.index'),
        "icon" => "",
        "role" => "Administrator",
      ],
    ]
  ],
  [
    "title" => "Menu Transaksi",
    "link" => "#",
    "icon" => "fas fa-th",
    "children" => [
      [
        "title" => "Peminjaman",
        "link" => route('peminjaman.index'),
        "icon" => "",
      ],
      [
        "title" => "Tabungan",
        "link" => route('tabungan.index'),
        "icon" => "",
      ],
    ]
  ],
  [
    "title" => "Report",
    "link" => "#",
    "icon" => ""
  ],
  [
    "title" => "Setting",
    "link" => "#",
    "icon" => "fas fa-cogs",
    "children" => [
      [
        "title" => "Base Setting",
        "link" => "#",
        "icon" => "fas fa-cog",
      ],
      [
        "title" => "Ganti Password",
        "link" => route('auth.change_password.form'),
        "icon" => "fas fa-cog",
      ]
    ]
  ]
];

?>



  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <?= HtmlHelper::generateSidebar($sidebar) ?>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>